config/routes.rb
Rails.application.routes.draw do
  root to: "catalogs#index"
  resources :authors
  resources :books
end

app/models/author.rb
class Author < ActiveRecord::Base
  validates :first_name, presence: true
  validates :last_name, presence: true
  has_many :publications, dependent: :destroy
  has_many :books, through: :publications


  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :publisher
  has_many :publications, dependent: :destroy
  has_many :authors, through: :publications

  validates :title, presence: true
  validates :isbn, presence: true
  validates :description, presence: true
  validates :published_at, presence: true
  validates :publisher_id, presence: true
  validates :page_count, numericality: { only_integer: true, greater_than: 0}
  validates :price, numericality: { greater_than_or_equal_to: 0.0}

  mount_uploader :book_cover, BookCoverUploader
end

app/models/publication.rb
class Publication < ActiveRecord::Base
  belongs_to :author
  belongs_to :book
  
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  has_many :books

  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, except: [:index, :new, :create]

  def index
  end

  def show
    #require 'pry';binding.pry
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      flash[:success] = "Author has been created"
      redirect_to @author
    else
      flash[:danger] = "Author has not been created"
      render :new
    end
  end

  def edit
  end

  def update
    if @author.update(author_params)
      flash[:success] = "Author has been updated"
      redirect_to @author
    else
      flash[:danger] = "Author has not been updated"
      render :edit
    end
  end

  def destroy
    @author.destroy
    flash[:success] = "Author has been deleted"
    redirect_to authors_path
  end


  private
  def author_params
    params.require(:author).permit(:first_name, :last_name)
  end

  def set_author
    @author = Author.find(params[:id])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, except: [:index, :new, :create]
  def index
    @books = Book.all
  end

  def show
  end

  def new
    @book = Book.new
    @publishers = Publisher.all
    @authors = Author.all
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:success] = 'Book has been created'
      redirect_to @book
    else
      flash.now[:danger] = 'Book has not been created'
      @publishers = Publisher.all
      @authors = Author.all
      render :new
    end
  end

  def edit
    @author = Author.all
  end

  def update
    if @book.update(book_params)
      flash[:success] = 'Book has been updated'
      redirect_to @book
    else
      flash[:danger] = 'Book has not been updated'
      render :edit
    end

  end
  def destroy
    if @book.destroy
      flash[:success] = 'Book has been deleted'
      redirect_to books_path
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :isbn, :page_count, :price, :description,
    :published_at, :publisher_id, :book_cover)
  end

  def set_book
    @book = Book.find(params[:id])
  end
end

app/controllers/catalogs_controller.rb
class CatalogsController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/_form.html.erb
<%= bootstrap_form_for(@author, :html => { class: 'form-horizonal'}) do |f| %>
<div class='form-group'>
  <label for='first_name' class='control-label col-md-3'>First name</label>
  <div class='col-md-9'>
    <%= f.text_field :first_name, class: 'form-control', hide_label: true %>
  </div>
</div>

<div class='form-group'>
  <label for='last_name' class='control-label col-md-3'>Last name</label>
  <div class='col-md-9'>
    <%= f.text_field :last_name, class: 'form-control', hide_label: true %>
  </div>
</div>

<div class='form-group actions control-group'>
  <div class='col-md-offset-3'>
    <%= f.submit class: 'btn btn-primary' %>
  </div>
</div>
<% end %>

app/views/authors/edit.html.erb
<div class="row">
  <h3 class="text-center titles">Add New Author</h3>
</div>

<div class="row">
  <div class="col-md-12">
    <%= render "form" %>
  </div>
</div>

app/views/authors/index.html.erb
<%= link_to "Add New author", new_author_path %>

app/views/authors/new.html.erb
<div class="row">
  <h3 class="text-center titles">Add New Author</h3>
</div>

<div class="row">
  <div class="col-md-12">
    <%= render "form" %>
  </div>
</div>

app/views/books/_form.html.erb
<%= bootstrap_form_for(@book, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class='form-group'>
    <label class='control-label col-sm-3'>Title</label>
    <div class='col-sm-9'>
      <%= f.text_field :title, class: 'form-control', hide_label: true, placeholder: 'Title of the book', autofocus: true %>
    </div>
  </div>
  <div class='form-group'>
    <label class='control-label col-sm-3'>Isbn</label>
    <div class='col-sm-9'>
      <%= f.text_field :isbn, class: 'form-control', hide_label: true, placeholder: 'Book ISBN' %>
    </div>
  </div>
  <div class='form-group'>
    <label class='control-label col-sm-3'>Page count</label>
    <div class='col-sm-9'>
      <%= f.text_field :page_count, class: 'form-control', hide_label: true, placeholder: 'Number of pages' %>
    </div>
  </div>
  <div class='form-group'>
    <label class='control-label col-sm-3'>Price</label>
    <div class='col-sm-9'>
      <%= f.text_field :price, class: 'form-control', hide_label: true, placeholder: 'Book unit price' %>
    </div>
  </div>
  <div class='form-group'>
    <label class='control-label col-sm-3'>Description</label>
    <div class='col-sm-9'>
      <%= f.text_area :description, class: 'form-control', hide_label: true, placeholder: 'Book description' %>
    </div>
  </div>
  <div class='form-group'>
    <label class='control-label col-sm-3'>Publication date</label>
    <div class='col-sm-9'>
      <%= f.text_field :published_at, placeholder: 'Date format: yyyy-mm-dd', class: 'form-control', hide_label: true %>
    </div>
  </div>

  <div class='form-group'>
    <label class='control-label col-sm-3'>Publisher</label>
    <div class='col-sm-9'>
      <%= f.select :publisher_id, @publishers.map { |p| [p.name, p.id] },
                      prompt: 'Select a publisher', class: 'form-control', hide_label: true %>
    </div>
  </div>

  <div class='form-group'>
    <label class='control-label col-sm-3'>Book cover</label>
    <div class='col-sm-9'>
      <%= f.file_field :book_cover, placeholder: 'Book cover', class: 'form-control', hide_label: true %>
    </div>
  </div>

  <div class='form-group'>
    <label class='control-label col-sm-3'>Authors</label>
    <div class='col-sm-9'>
      <%= f.collection_check_boxes :author_ids, @authors, :id, :full_name, class: 'form-control', hide_label: true %>
    </div>
  </div>

  <%# end %>
  <div class='form-group actions control-group'>
    <div class='col-sm-offset-3'>
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/books/index.html.erb
<%= link_to "Add New book", new_book_path %>

app/views/books/new.html.erb
<div class="row">
  <h3 class="text-center titles">Add New Book</h3>
</div>

<div class="row">
  <div class="col-md-12">
    <%= render "form" %>
  </div>
</div>

app/views/books/show.html.erb
<h1>Book Show Page</h1>

app/views/catalogs/index.html.erb
<h1>Catalog Index Page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bookstore</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= yield :head %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'shared/header' %>

    <%= render 'shared/main' %>

    <%= render 'shared/footer' %>

  </body>
</html>

app/views/shared/_footer.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-10 col-md-offset-1'>
      <footer role="contentinfo">
        <p class="text-center"><small>Copyright &copy; Darth Vader</small></p>
      </footer>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<header role="banner">
  <nav role="navigation" class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Bookstore App", root_path, class: "navbar-brand" %>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Home", root_path %></li>
          <li><%= link_to "Authors", authors_path %></li>
          <li><%= link_to "Books", books_path %></li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_main.html.erb
<main role="main">
  <div class='container'>
    <%= render 'shared/messages' %>
    <div class='row'>

      <div class='col-md-9'>
        <% if content_for?(:sidebar) %>
          <div class='col-md-3'>
            <%= yield :sidebar %>
          </div>
          <div class='col-md-9'>
            <%= yield %>
          </div>
        <% else %>
          <div class='col-md-10 col-md-offset-1'>
            <%= yield %>
          </div>
        <% end %>
      </div>

      <div class='col-md-3'>
        <div id="cart">
        </div>
      </div>

    </div>
  </div>
</main>

app/views/shared/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class='alert alert-<%="#{name}" %>'>
    <a href='#' class='close' data-dismiss='alert'>&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>